--- #YAML:1.0
name:                Text-SenseClusters
version:             0.96
abstract:            SenseClusters - Clustering contextually similar text instances.
license:             ~
author:              
    - Ted Pedersen <tpederse at d.umn.edu>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Algorithm::Munkres:            0.06
    Algorithm::RandomMatrixGeneration: 0.04
    Bit::Vector:                   6.3
    Math::BigFloat:                1.51
    Math::SparseMatrix:            0.01
    Math::SparseVector:            0.03
    PDL:                           2.4.1
    Set::Scalar:                   1.19
    Text::NSP:                     1.01
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
