=head1 Name

README.Flows.pod

=head1 Description

Contains the sequence diagrams for SenseClusters in .fig and .pdf format -
flowchart.fig, flowchart.pdf

The above files show the sequence of commands to run a complete experiment
and possible variations in feature, context and clustering type.

=head1 ACKNOWLEDGMENTS

This work has been partially supported by a National Science Foundation
Faculty Early CAREER Development award (Grant #0092784).

=cut

